version: "3"

services:
  web:
    build: ./flask-project
    ports:
      - "5000:5000"
    links:
      - postgres:postgres
    env_file:
      - .env
    depends_on:
      - postgres
    #command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app
    #command: python app.py

  data:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    command: "true"

  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:
